# Bibliotecas

In [1]:
import pandas as pd
import numpy as np
import matplotlib as plt

## Biblioteca para conexão com banco de dados

In [2]:
from sqlalchemy import create_engine

# Conexão com Banco de Dados MySQL

In [3]:
usuario = "root"
senha = "195616"
host = "localhost"
porta = "3306"
database = "restaurante"

engine = create_engine(f"mysql+pymysql://{usuario}:{senha}@{host}:{porta}/{database}")

# Importação dos dados e Analise exploratória inicial

## Cidades

In [4]:
df_cidades_raw = pd.read_sql("SELECT * FROM cidades", engine)
df_cidades_raw.head()

   id            city
0   1        Tel Aviv
1   2       Ramat Gan
2   3  Ramat Hasharon
3   4        Herzelia
4   5       Givatayim

In [5]:
df_cidades_raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      5 non-null      int64
 1   city    5 non-null      object
dtypes: int64(1), object(1)
memory usage: 212.0+ bytes

In [6]:
display(df_cidades_raw)

   id            city
0   1        Tel Aviv
1   2       Ramat Gan
2   3  Ramat Hasharon
3   4        Herzelia
4   5       Givatayim

## Detalhes Pedidos

In [7]:
df_dtl_pedidos_raw = pd.read_sql("SELECT * FROM detalhes_pedido", engine)
df_dtl_pedidos_raw.head()

   id  order_id  meal_id
0   1         3      176
1   2         5      349
2   3         5      348
3   4         5      344
4   5         5      348

In [8]:
df_dtl_pedidos_raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70577 entries, 0 to 70576
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        70577 non-null  int64
 1   order_id  70577 non-null  int64
 2   meal_id   70577 non-null  int64
dtypes: int64(3)
memory usage: 1.6 MB

In [9]:
display(df_dtl_pedidos_raw)

          id  order_id  meal_id
0          1         3      176
1          2         5      349
2          3         5      348
3          4         5      344
4          5         5      348
...      ...       ...      ...
70572  70573     35998       96
70573  70574     35999       22
70574  70575     36000       10
70575  70576     36000        4
70576  70577     36000        5

[70577 rows x 3 columns]

## Membros

In [10]:
df_membros_raw = pd.read_sql("SELECT * FROM membros", engine)
df_membros_raw.head()

,id,first_name,surname,sex,email,city_id,monthly_budget
0,1,Ollie,Kinney,M,Ol.Kinney@walla.co.il,4,1000.0
1,2,Landon,Bishop,F,La.Bi@gmail.com,4,500.0
2,3,Jia,Delarosa,M,Jia.De@gmail.com,4,500.0
3,4,Valentina,Ratcliffe,F,Va.Ratcliffe@gmail.com,4,600.0
4,5,Stacie,Patel,F,St.Patel@hotmail.com,3,500.0

In [11]:
df_membros_raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              200 non-null    int64
 1   first_name      200 non-null    object
 2   surname         200 non-null    object
 3   sex             200 non-null    object
 4   email           200 non-null    object
 5   city_id         200 non-null    int64
 6   monthly_budget  200 non-null    float64
dtypes: float64(1), int64(2), object(4)
memory usage: 11.1+ KB

In [12]:
display(df_membros_raw)

,id,first_name,surname,sex,email,city_id,monthly_budget
0,1,Ollie,Kinney,M,Ol.Kinney@walla.co.il,4,1000.0
1,2,Landon,Bishop,F,La.Bi@gmail.com,4,500.0
2,3,Jia,Delarosa,M,Jia.De@gmail.com,4,500.0
3,4,Valentina,Ratcliffe,F,Va.Ratcliffe@gmail.com,4,600.0
4,5,Stacie,Patel,F,St.Patel@hotmail.com,3,500.0
...,...,...,...,...,...,...,...
195,196,Juan,Barlow,M,Juan.Ba@yahoo.com,4,500.0
196,197,Natalia,Daniel,F,Natalia.Da@gmail.com,4,500.0
197,198,Drew,Begum,M,Drew.Begum@gmail.com,3,800.0
198,199,Nial,Meadows,M,Nial.Me@yahoo.com,5,500.0
199,200,Diya,Myers,F,Diya.My@walla.co.il,5,600.0

## Pedidos

In [13]:
df_pedidos_raw = pd.read_sql("SELECT * FROM pedidos", engine)
df_pedidos_raw.head()

   id        date              hour  member_id  restaurant_id  total_order
0   1  2020-01-01  11:00:00.0000000         25              6          0.0
1   2  2020-01-01  11:08:00.0000000        122              4          0.0
2   3  2020-01-01  11:10:00.0000000         62             16         39.0
3   4  2020-01-01  11:13:00.0000000        171              9          0.0
4   5  2020-01-01  11:13:00.0000000        152             30        153.0

In [14]:
df_pedidos_raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36000 entries, 0 to 35999
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             36000 non-null  int64
 1   date           36000 non-null  object
 2   hour           36000 non-null  object
 3   member_id      36000 non-null  int64
 4   restaurant_id  36000 non-null  int64
 5   total_order    36000 non-null  float64
dtypes: float64(1), int64(3), object(2)
memory usage: 1.6+ MB

In [15]:
display(df_pedidos_raw)

,id,date,hour,member_id,restaurant_id,total_order
0,1,2020-01-01,11:00:00.0000000,25,6,0.00
1,2,2020-01-01,11:08:00.0000000,122,4,0.00
2,3,2020-01-01,11:10:00.0000000,62,16,39.00
3,4,2020-01-01,11:13:00.0000000,171,9,0.00
4,5,2020-01-01,11:13:00.0000000,152,30,153.00
...,...,...,...,...,...,...
35995,35996,2020-07-01,23:29:00.0000000,22,14,159.82
35996,35997,2020-07-01,23:33:00.0000000,44,2,92.43
35997,35998,2020-07-01,23:34:00.0000000,199,10,46.14
35998,35999,2020-07-01,23:40:00.0000000,86,3,33.51
35999,36000,2020-07-01,23:41:00.0000000,135,1,112.59

## Refeições

In [15]:
df_refeicoes_raw = pd.read_sql("SELECT * FROM refeicoes", engine)
df_refeicoes_raw.head()

   id  restaurant_id  serve_type_id  meal_type_id hot_cold meal_name  price
0   1              1              1             2     Cold    Meal 1  43.22
1   2              1              2             4      Hot    Meal 2  29.22
2   3              1              3             1     Cold    Meal 3  37.34
3   4              1              3             2      Hot    Meal 4  52.41
4   5              1              3             2     Cold    Meal 5  27.75

In [16]:
df_refeicoes_raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 350 entries, 0 to 349
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             350 non-null    int64
 1   restaurant_id  350 non-null    int64
 2   serve_type_id  350 non-null    int64
 3   meal_type_id   350 non-null    int64
 4   hot_cold       350 non-null    object
 5   meal_name      350 non-null    object
 6   price          350 non-null    float64
dtypes: float64(1), int64(4), object(2)
memory usage: 19.3+ KB

In [17]:
display(df_refeicoes_raw)

      id  restaurant_id  serve_type_id  meal_type_id hot_cold meal_name  price
0      1              1              1             2     Cold    Meal 1  43.22
1      2              1              2             4      Hot    Meal 2  29.22
2      3              1              3             1     Cold    Meal 3  37.34
3      4              1              3             2      Hot    Meal 4  52.41
4      5              1              3             2     Cold    Meal 5  27.75
..   ...            ...            ...           ...      ...       ...    ...
345  346             30              3             1     Cold  Meal 346  68.34
346  347             30              2             2      Hot  Meal 347  70.82
347  348             30              1             1     Cold  Meal 348  37.15
348  349             30              2             1     Cold  Meal 349  54.51
349  350             30              2             3     Cold  Meal 350  59.53

[350 rows x 7 columns]

## Restaurantes

In [18]:
df_restaurantes_raw = pd.read_sql("SELECT * FROM restaurantes", engine)
df_restaurantes_raw.head()

   id restaurant_name  restaurant_type_id  income_persentage  city_id
0   1    Restaurant 1                   3              0.075        3
1   2    Restaurant 2                   5              0.100        3
2   3    Restaurant 3                   2              0.075        4
3   4    Restaurant 4                   4              0.100        4
4   5    Restaurant 5                   5              0.050        2

In [19]:
df_restaurantes_raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   id                  30 non-null     int64
 1   restaurant_name     30 non-null     object
 2   restaurant_type_id  30 non-null     int64
 3   income_persentage   30 non-null     float64
 4   city_id             30 non-null     int64
dtypes: float64(1), int64(3), object(1)
memory usage: 1.3+ KB

In [20]:
display(df_restaurantes_raw)

    id restaurant_name  restaurant_type_id  income_persentage  city_id
0    1    Restaurant 1                   3              0.075        3
1    2    Restaurant 2                   5              0.100        3
2    3    Restaurant 3                   2              0.075        4
3    4    Restaurant 4                   4              0.100        4
4    5    Restaurant 5                   5              0.050        2
5    6    Restaurant 6                   1              0.050        2
6    7    Restaurant 7                   1              0.100        4
7    8    Restaurant 8                   2              0.075        5
8    9    Restaurant 9                   1              0.075        4
9   10   Restaurant 10                   4              0.100        2
10  11   Restaurant 11                   5              0.075        4
11  12   Restaurant 12                   5              0.075        3
12  13   Restaurant 13                   5              0.075        3
13  14   Restaurant 14                   1              0.050        3
14  15   Restaurant 15                   1              0.100        4
15  16   Restaurant 16                   1              0.075        3
16  17   Restaurant 17                   1              0.050        2
17  18   Restaurant 18                   3              0.050        3
18  19   Restaurant 19                   2              0.100        2
19  20   Restaurant 20                   1              0.075        2
20  21   Restaurant 21                   2              0.050        1
21  22   Restaurant 22                   1              0.075        5
22  23   Restaurant 23                   1              0.100        1
23  24   Restaurant 24                   3              0.050        1
24  25   Restaurant 25                   3              0.100        4
25  26   Restaurant 26                   2              0.075        1
26  27   Restaurant 27                   5              0.100        4
27  28   Restaurant 28                   2              0.100        1
28  29   Restaurant 29                   2              0.050        5
29  30   Restaurant 30                   4              0.075        1

## Tipos de Refeição

In [21]:
df_tp_refeicao_raw = pd.read_sql("SELECT * FROM tipos_de_refeicao", engine)
df_tp_refeicao_raw.head()

   id meal_type
0   1     Vegan
1   2    Cheese
2   3      Beef
3   4   Chicken

In [22]:
df_tp_refeicao_raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   id         4 non-null      int64
 1   meal_type  4 non-null      object
dtypes: int64(1), object(1)
memory usage: 196.0+ bytes

In [23]:
display(df_tp_refeicao_raw)

   id meal_type
0   1     Vegan
1   2    Cheese
2   3      Beef
3   4   Chicken

## Tipos de Restaurante

In [24]:
df_tp_restaurante_raw = pd.read_sql("SELECT * FROM tipos_de_restaurante", engine)
df_tp_restaurante_raw.head()

   id restaurant_type
0   1       Fast Food
1   2           Asian
2   3         Italian
3   4        Homemade
4   5          Indian

In [25]:
df_tp_restaurante_raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 2 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               5 non-null      int64
 1   restaurant_type  5 non-null      object
dtypes: int64(1), object(1)
memory usage: 212.0+ bytes

In [26]:
display(df_tp_restaurante_raw)

   id restaurant_type
0   1       Fast Food
1   2           Asian
2   3         Italian
3   4        Homemade
4   5          Indian

## Tipos de Serviço

In [27]:
df_tp_servico_raw = pd.read_sql("SELECT * FROM tipos_servico", engine)
df_tp_servico_raw.head()

   id serve_type
0   1    Starter
1   2       Main
2   3     Desert

In [28]:
df_tp_servico_raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          3 non-null      int64
 1   serve_type  3 non-null      object
dtypes: int64(1), object(1)
memory usage: 180.0+ bytes

In [29]:
display(df_tp_servico_raw)

   id serve_type
0   1    Starter
1   2       Main
2   3     Desert

## Total Mensal Membros

In [30]:
df_ttl_mens_membros_raw = pd.read_sql("SELECT * FROM total_mensal_membros", engine)
df_ttl_mens_membros_raw.head()

,member_id,first_name,surname,sex,email,city,year,month,order_count,meals_count,monthly_budget,total_expense,balance,commission
0,47,Joyce,Newton,F,Joyce.Ne@gmail.com,Herzelia,2020,1,17,37,1836.15,500.0,-1336.15,136.27950
1,126,Macey,Almond,M,Macey.Almond@yahoo.com,Tel Aviv,2020,1,30,64,2676.98,1000.0,-1676.98,214.98500
2,68,Aydin,Hirst,M,Aydin.Hirst@hotmail.com,Tel Aviv,2020,1,24,52,2286.53,1000.0,-1286.53,164.93850
3,193,Mira,Kent,M,Mi.Kent@walla.co.il,Tel Aviv,2020,1,24,54,2547.62,500.0,-2047.62,193.59125
4,53,Lilly-Ann,Frey,F,Li.Fr@hotmail.com,Tel Aviv,2020,1,23,50,2456.64,1000.0,-1456.64,193.97650

In [31]:
df_ttl_mens_membros_raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   member_id       1200 non-null   int64
 1   first_name      1200 non-null   object
 2   surname         1200 non-null   object
 3   sex             1200 non-null   object
 4   email           1200 non-null   object
 5   city            1200 non-null   object
 6   year            1200 non-null   int64
 7   month           1200 non-null   int64
 8   order_count     1200 non-null   int64
 9   meals_count     1200 non-null   int64
 10  monthly_budget  1200 non-null   float64
 11  total_expense   1200 non-null   float64
 12  balance         1200 non-null   float64
 13  commission      1200 non-null   float64
dtypes: float64(4), int64(5), object(5)
memory usage: 131.4+ KB

In [32]:
display(df_ttl_mens_membros_raw)

,member_id,first_name,surname,sex,email,city,year,month,order_count,meals_count,monthly_budget,total_expense,balance,commission
0,47,Joyce,Newton,F,Joyce.Ne@gmail.com,Herzelia,2020,1,17,37,1836.15,500.0,-1336.15,136.27950
1,126,Macey,Almond,M,Macey.Almond@yahoo.com,Tel Aviv,2020,1,30,64,2676.98,1000.0,-1676.98,214.98500
2,68,Aydin,Hirst,M,Aydin.Hirst@hotmail.com,Tel Aviv,2020,1,24,52,2286.53,1000.0,-1286.53,164.93850
3,193,Mira,Kent,M,Mi.Kent@walla.co.il,Tel Aviv,2020,1,24,54,2547.62,500.0,-2047.62,193.59125
4,53,Lilly-Ann,Frey,F,Li.Fr@hotmail.com,Tel Aviv,2020,1,23,50,2456.64,1000.0,-1456.64,193.97650
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1195,185,Subhaan,Washington,M,Su.Wa@hotmail.com,Givatayim,2020,6,28,62,2569.51,500.0,-2069.51,200.62300
1196,62,Janine,Coulson,F,Ja.Coulson@gmail.com,Herzelia,2020,6,30,73,3286.34,500.0,-2786.34,242.53925
1197,145,Taran,Samuels,F,Ta.Samuels@hotmail.com,Herzelia,2020,6,27,61,2660.16,600.0,-2060.16,195.61925
1198,169,Emaan,Greenaway,M,Emaan.Greenaway@gmail.com,Herzelia,2020,6,25,67,2714.56,500.0,-2214.56,216.15675
1199,86,Keir,Ewing,M,Keir.Ewing@walla.co.il,Ramat Hasharon,2020,6,31,65,2843.16,800.0,-2043.16,223.22450

# Trocando nomes das colunas

In [33]:
# Cidades
df_cidades_raw.columns = ['id', 'cidades']
df_cidades_raw.head()

   id         cidades
0   1        Tel Aviv
1   2       Ramat Gan
2   3  Ramat Hasharon
3   4        Herzelia
4   5       Givatayim

In [35]:
# Detalhes Pedidos
df_dtl_pedidos_raw.columns = ['id', 'id_pedido', 'id_refeicao']
df_dtl_pedidos_raw.head()

   id  id_pedido  id_refeicao
0   1          3          176
1   2          5          349
2   3          5          348
3   4          5          344
4   5          5          348

In [36]:
# Membros
df_membros_raw.columns = ['id', 'nome', 'sobrenome', 'genero', 'email', 'cidade', 'orcamento_mensal']
df_membros_raw.head()

,id,nome,sobrenome,genero,email,cidade,orcamento_mensal
0,1,Ollie,Kinney,M,Ol.Kinney@walla.co.il,4,1000.0
1,2,Landon,Bishop,F,La.Bi@gmail.com,4,500.0
2,3,Jia,Delarosa,M,Jia.De@gmail.com,4,500.0
3,4,Valentina,Ratcliffe,F,Va.Ratcliffe@gmail.com,4,600.0
4,5,Stacie,Patel,F,St.Patel@hotmail.com,3,500.0

In [37]:
# Pedidos
df_pedidos_raw.columns = ['id', 'data', 'hora', 'id_membro', 'id_restaurante', 'valor_pedido']
df_pedidos_raw.head()

   id        data              hora  id_membro  id_restaurante  valor_pedido
0   1  2020-01-01  11:00:00.0000000         25               6           0.0
1   2  2020-01-01  11:08:00.0000000        122               4           0.0
2   3  2020-01-01  11:10:00.0000000         62              16          39.0
3   4  2020-01-01  11:13:00.0000000        171               9           0.0
4   5  2020-01-01  11:13:00.0000000        152              30         153.0

In [38]:
# Refeições
df_refeicoes_raw.columns = ['id', 'id_restaurante', 'id_tp_servico', 'id_tp_refeicao', 'quente_frio', 'nome_refeicao', 'preco']
df_refeicoes_raw.head()

,id,id_restaurante,id_tp_servico,id_tp_refeicao,quente_frio,nome_refeicao,preco
0,1,1,1,2,Cold,Meal 1,43.22
1,2,1,2,4,Hot,Meal 2,29.22
2,3,1,3,1,Cold,Meal 3,37.34
3,4,1,3,2,Hot,Meal 4,52.41
4,5,1,3,2,Cold,Meal 5,27.75

In [39]:
# Restaurantes
df_restaurantes_raw.columns = ['id', 'nome_restaurante', 'id_tp_restaurante', 'renda_percentual', 'id_cidade']
df_restaurantes_raw.head()

   id nome_restaurante  id_tp_restaurante  renda_percentual  id_cidade
0   1     Restaurant 1                  3             0.075          3
1   2     Restaurant 2                  5             0.100          3
2   3     Restaurant 3                  2             0.075          4
3   4     Restaurant 4                  4             0.100          4
4   5     Restaurant 5                  5             0.050          2

In [40]:
# Tipos de Refeição
df_tp_refeicao_raw.columns = ['id', 'tp_refeicao']
df_tp_refeicao_raw.head()

   id tp_refeicao
0   1       Vegan
1   2      Cheese
2   3        Beef
3   4     Chicken

In [41]:
# Tipos de Restaurante
df_tp_restaurante_raw.columns = ['id', 'tp_restaurante']
df_tp_restaurante_raw.head()

   id tp_restaurante
0   1      Fast Food
1   2          Asian
2   3        Italian
3   4       Homemade
4   5         Indian

In [42]:
# Tipos de Serviço
df_tp_servico_raw.columns = ['id', 'tp_servico']
df_tp_servico_raw.head()

   id tp_servico
0   1    Starter
1   2       Main
2   3     Desert

In [43]:
# Total Mensal de Membros
df_ttl_mens_membros_raw.columns = ['id_membro', 'nome', 'sobrenome', 'genero', 'email', 'cidade', 'ano', 'mes', 
                                   'qtd_pedidos', 'qtd_refeicoes', 'orcamento_mensal', 'despesa_total', 'saldo', 'comissao']
df_ttl_mens_membros_raw.head()

,id_membro,nome,sobrenome,genero,email,cidade,ano,mes,qtd_pedidos,qtd_refeicoes,orcamento_mensal,despesa_total,saldo,comissao
0,47,Joyce,Newton,F,Joyce.Ne@gmail.com,Herzelia,2020,1,17,37,1836.15,500.0,-1336.15,136.27950
1,126,Macey,Almond,M,Macey.Almond@yahoo.com,Tel Aviv,2020,1,30,64,2676.98,1000.0,-1676.98,214.98500
2,68,Aydin,Hirst,M,Aydin.Hirst@hotmail.com,Tel Aviv,2020,1,24,52,2286.53,1000.0,-1286.53,164.93850
3,193,Mira,Kent,M,Mi.Kent@walla.co.il,Tel Aviv,2020,1,24,54,2547.62,500.0,-2047.62,193.59125
4,53,Lilly-Ann,Frey,F,Li.Fr@hotmail.com,Tel Aviv,2020,1,23,50,2456.64,1000.0,-1456.64,193.97650

# Identificando valores nulos

In [44]:
# Cidades
df_cidades_raw.isnull().sum()

id         0
cidades    0
dtype: int64

In [45]:
# Detalhes Pedidos
df_dtl_pedidos_raw.isnull().sum()

id             0
id_pedido      0
id_refeicao    0
dtype: int64

In [46]:
# Membros
df_membros_raw.isnull().sum()

id                  0
nome                0
sobrenome           0
genero              0
email               0
cidade              0
orcamento_mensal    0
dtype: int64

In [47]:
# Pedidos
df_pedidos_raw.isnull().sum()

id                0
data              0
hora              0
id_membro         0
id_restaurante    0
valor_pedido      0
dtype: int64

In [48]:
# Refeições
df_refeicoes_raw.isnull().sum()

id                0
id_restaurante    0
id_tp_servico     0
id_tp_refeicao    0
quente_frio       0
nome_refeicao     0
preco             0
dtype: int64

In [49]:
# Restaurantes
df_restaurantes_raw.isnull().sum()

id                   0
nome_restaurante     0
id_tp_restaurante    0
renda_percentual     0
id_cidade            0
dtype: int64

In [50]:
# Tipo de Refeição
df_tp_refeicao_raw.isnull().sum()

id             0
tp_refeicao    0
dtype: int64

In [51]:
# Tipo de Restaurante
df_tp_restaurante_raw.isnull().sum()

id                0
tp_restaurante    0
dtype: int64

In [52]:
# Tipo de Serviço
df_tp_servico_raw.isnull().sum()

id            0
tp_servico    0
dtype: int64

In [53]:
# Total Mensal de Membros
df_ttl_mens_membros_raw.isnull().sum()

id_membro           0
nome                0
sobrenome           0
genero              0
email               0
cidade              0
ano                 0
mes                 0
qtd_pedidos         0
qtd_refeicoes       0
orcamento_mensal    0
despesa_total       0
saldo               0
comissao            0
dtype: int64